version: '3'
services:
  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - .:/srv/app
    links:
      - mysql:mysql
  mysql:
    image: mysql:5.7
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=freecodetube
      - MYSQL_USER=freecodetube
      - MYSQL_PASSWORD=secret
